language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "nightly"
  - "pypy"
# command to run tests
script: nosetests
deploy:
  provider: pypi
  user:
    secure: ""
  password:
    secure: ""
  on:
    tags: true
